### ISSUE TITLE
 docutils version issue

### ISSUE THREAD

**Issue by citicruiser** [Netflix/repokid#244]
I installed repokid on AWS Linux2 with python 3.7.5 (also tried 3.6.6), but got below error when ran python setup.py develop

*********************************************************
Installed /home/ec2-user/virtualenvs/repokid/lib/python3.7/site-packages/python_dateutil-2.8.1-py3.7.egg
error: docutils 0.16rc1 is installed but docutils<0.16,>=0.10 is required by {'botocore'}
*********************************************************

I revert the commit back to 7f67f551d5192a7318a816f0665e8d0b388af6cc, and the problem went away.  Any idea?

**Comment by castrapel** [comment]
What happens if you install with `pip install -e`? If this works for you, I may update the README. It is highly recommended to use pip install . (install) and pip install -e . (developer install) to install packages, as invoking setup.py directly often does the wrong things for many dependencies, such as pull prereleases and incompatible package versions, or make the package hard to uninstall with pip.

**Comment by citicruiser** [comment]
new to python and repokid.  Please forgive me my ignorance.

Are you suggesting to run 'pip install -e . ' instead of 'python setup.py develop'?

**Comment by patricksanders** [comment]
Yeah, try that to see if pip handles the dependency resolution any better. I was able to replicate the error you got with `python setup.py develop` in a clean environment, but `pip install -e .` worked.

**Comment by citicruiser** [comment]
yep. pip install -e .  does work for me.  thank you so much.
